apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ivy-redis-deployment.yaml
  - ivy-redis-service.yaml
  - ivy-redis-insight-deployment.yaml
  - ivy-redis-insight-service.yaml
  - ivy-sysdb-deployment.yaml
  - ivy-sysdb-service.yaml
  - ivy-engine-service.yaml
  - ivy-engine-deployment.yaml
  - ivy-engine-ingress.yaml
  
configMapGenerator:
- name: ivy-configmap
  files:
  - redisson.conf
  - ivy.yaml
  - license.lic